        -:    0:Source:D:/UBB-FMI/An I/Sem II/OOP/Exercitii/untitled1/main.cpp
        -:    0:Graph:D:\UBB-FMI\An I\Sem II\OOP\Exercitii\untitled1\cmake-build-debug-coverage\CMakeFiles\untitled1.dir\main.cpp.gcno
        -:    0:Data:D:\UBB-FMI\An I\Sem II\OOP\Exercitii\untitled1\cmake-build-debug-coverage\CMakeFiles\untitled1.dir\main.cpp.gcda
        -:    0:Runs:1
        -:    1:#include <iostream>
        -:    2:#include <vector>
        -:    3:#include <exception>
        -:    4:#include <cassert>
        -:    5:using namespace std;
        -:    6:
function _Z1fi called 3 returned 67% blocks executed 87%
        3:    7:vector<int> f(int a)
        -:    8:{
        3:    9:    if(a < 0)
        3:    9-block  0
branch  0 taken 1 (fallthrough)
branch  1 taken 2
        1:   10:        throw exception();
        1:   10-block  0
call    0 returned 1
call    1 returned 1
call    2 returned 0
        2:   11:    vector<int>rez;
        2:   11-block  0
call    0 returned 2
        8:   12:    for(int i=1; i<=a; i++)
        6:   12-block  0
        8:   12-block  1
branch  0 taken 6
branch  1 taken 2 (fallthrough)
        6:   13:        if(a%i == 0)
        6:   13-block  0
branch  0 taken 4 (fallthrough)
branch  1 taken 2
        4:   14:            rez.push_back(i);
        4:   14-block  0
call    0 returned 4
branch  1 taken 4 (fallthrough)
branch  2 taken 0 (throw)
        2:   15:    return rez;
        2:   15-block  0
        2:   15-block  1
    =====:   16:}
    $$$$$:   16-block  0
call    0 never executed
        -:   17:
function main called 1 returned 100% blocks executed 67%
        1:   18:int main()
        -:   19:{
        -:   20:    try{
       1*:   21:        f(-1);
        1:   21-block  0
call    0 returned 1
branch  1 taken 0 (fallthrough)
branch  2 taken 1 (throw)
    %%%%%:   21-block  1
call    3 never executed
        1:   21-block  2
        -:   22:    }
        1:   23:    catch (exception& e){
        1:   23-block  0
branch  0 taken 0 (fallthrough)
branch  1 taken 1
        1:   23-block  1
call    2 returned 1
        1:   24:        cout << "Exception caught\n";
call    0 returned 1
branch  1 taken 1 (fallthrough)
branch  2 taken 0 (throw)
        1:   25:    }
        1:   25-block  0
call    0 returned 1
    $$$$$:   25-block  1
call    1 never executed
        1:   26:    vector<int>rezz = f(0);
        1:   26-block  0
call    0 returned 1
branch  1 taken 1 (fallthrough)
branch  2 taken 0 (throw)
       1*:   27:    assert(rezz.empty());
        1:   27-block  0
call    0 returned 1
branch  1 taken 0 (fallthrough)
branch  2 taken 1
    %%%%%:   27-block  1
call    3 never executed
        1:   27-block  2
        1:   28:    vector<int>rez = f(6);
        1:   28-block  0
call    0 returned 1
branch  1 taken 1 (fallthrough)
branch  2 taken 0 (throw)
       1*:   29:    assert(rez.size() == 4);
        1:   29-block  0
call    0 returned 1
branch  1 taken 0 (fallthrough)
branch  2 taken 1
    %%%%%:   29-block  1
call    3 never executed
        1:   29-block  2
       1*:   30:    assert(rez[0] == 1);
        1:   30-block  0
call    0 returned 1
branch  1 taken 0 (fallthrough)
branch  2 taken 1
    %%%%%:   30-block  1
call    3 never executed
        1:   30-block  2
       1*:   31:    assert(rez[1] == 2);
        1:   31-block  0
call    0 returned 1
branch  1 taken 0 (fallthrough)
branch  2 taken 1
    %%%%%:   31-block  1
call    3 never executed
        1:   31-block  2
       1*:   32:    assert(rez[2] == 3);
        1:   32-block  0
call    0 returned 1
branch  1 taken 0 (fallthrough)
branch  2 taken 1
    %%%%%:   32-block  1
call    3 never executed
        1:   32-block  2
       1*:   33:    assert(rez[3] == 6);
        1:   33-block  0
call    0 returned 1
branch  1 taken 0 (fallthrough)
branch  2 taken 1
    %%%%%:   33-block  1
call    3 never executed
        1:   33-block  2
        1:   34:    return 0;
        1:   35:}
        1:   35-block  0
call    0 returned 1
call    1 returned 1
    $$$$$:   35-block  1
call    2 never executed
    $$$$$:   35-block  2
call    3 never executed
